### ISSUE TITLE
An Internal Server Error Occurred cakephp 3.7.7

### ISSUE THREAD

**Issue by latheefp** [maiconpinto/cakephp-adminlte-theme#81]
2019-04-26 06:03:13 Error: [Cake\Core\Exception\MissingPluginException] Plugin AdminLTE could not be found.
Exception Attributes: array (
  'plugin' => 'AdminLTE',
)
#0 H:\web\mahallu2\vendor\cakephp\cakephp\src\Core\Plugin.php(255): Cake\Core\PluginCollection->get('AdminLTE')
#1 H:\web\mahallu2\vendor\cakephp\cakephp\src\Core\App.php(190): Cake\Core\Plugin::classPath('AdminLTE')
#2 H:\web\mahallu2\vendor\cakephp\cakephp\src\View\View.php(1763): Cake\Core\App::path('Template', 'AdminLTE')
#3 H:\web\mahallu2\vendor\cakephp\cakephp\src\View\View.php(1577): Cake\View\View->_paths(NULL)
#4 H:\web\mahallu2\vendor\cakephp\cakephp\src\View\View.php(876): Cake\View\View->_getViewFileName('Error\\error500')
#5 H:\web\mahallu2\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(410): Cake\View\View->render('error500', 'error')
#6 H:\web\mahallu2\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(385): Cake\Error\ExceptionRenderer->_outputMessageSafe('error500')
#7 H:\web\mahallu2\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(244): Cake\Error\ExceptionRenderer->_outputMessage('error')
#8 H:\web\mahallu2\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(116): Cake\Error\ExceptionRenderer->render()
#9 H:\web\mahallu2\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(Error), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 H:\web\mahallu2\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#11 H:\web\mahallu2\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 H:\web\mahallu2\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#13 H:\web\mahallu2\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 H:\web\mahallu2\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 H:\web\mahallu2\webroot\index.php(40): Cake\Http\Server->run()
#16 {main}
Request URL: /

**Comment by latheefp** [comment]
updated wrong file instead of Application.php.
